<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore2xml"
    nsURI="http://www.eclipse.org/emf/2005/Ecore2XML" nsPrefix="ecore2xml">
  <eClassifiers xsi:type="ecore:EClass" name="XMLInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetNamespace" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xMLRepresentation" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        volatile="true" defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iDAttributeName" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecoreToXMLInfo" upperBound="-1"
        eType="#//ENamedElementToXMLInfoMapEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="noNamespacePackage" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"
        volatile="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENamedElementToXMLInfoMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//ENamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//XMLInfo"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
