/*globals define, _, WebGMEGlobal*/
/*jshint browser: true*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue Sep 26 2017 14:02:16 GMT-0500 (CDT).
 */

define([
    'js/PanelBase/PanelBaseWithHeader',
    'js/PanelManager/IActivePanel',
    'widgets/DeploymentEditor/DeploymentEditorWidget',
    './DeploymentEditorControl'
], function (
    PanelBaseWithHeader,
    IActivePanel,
    DeploymentEditorWidget,
    DeploymentEditorControl
) {
    'use strict';

    var DeploymentEditorPanel;

    DeploymentEditorPanel = function (layoutManager, params) {
        var options = {};
        //set properties from options
        options[PanelBaseWithHeader.OPTIONS.LOGGER_INSTANCE_NAME] = 'DeploymentEditorPanel';
        options[PanelBaseWithHeader.OPTIONS.FLOATING_TITLE] = true;

        //call parent's constructor
        PanelBaseWithHeader.apply(this, [options, layoutManager]);

        this._client = params.client;

        //initialize UI
        this._initialize();

        this.logger.debug('DeploymentEditorPanel ctor finished');
    };

    //inherit from PanelBaseWithHeader
    _.extend(DeploymentEditorPanel.prototype, PanelBaseWithHeader.prototype);
    _.extend(DeploymentEditorPanel.prototype, IActivePanel.prototype);

    DeploymentEditorPanel.prototype._initialize = function () {
        var self = this;

        this.widget = new DeploymentEditorWidget(this.$el, {toolBar: this.toolBar});

        this.widget.setTitle = function (title) {
            self.setTitle(title);
        };

        this.widget.onUIActivity = function () {
            WebGMEGlobal.PanelManager.setActivePanel(self);
            WebGMEGlobal.KeyboardManager.setListener(self.widget);
        };

        this.control = new DeploymentEditorControl({
            client: this._client,
            widget: this.widget
        });

        this.control.setReadOnly = function (isReadOnly) {
            self.setReadOnly(isReadOnly);
        };

        this.onActivate();
    };

    /* OVERRIDE FROM WIDGET-WITH-HEADER */
    /* METHOD CALLED WHEN THE WIDGET'S READ-ONLY PROPERTY CHANGES */
    DeploymentEditorPanel.prototype.onReadOnlyChanged = function (isReadOnly) {
        //apply parent's onReadOnlyChanged
        PanelBaseWithHeader.prototype.onReadOnlyChanged.call(this, isReadOnly);

    };

    DeploymentEditorPanel.prototype.onResize = function (width, height) {
        this.logger.debug('onResize --> width: ' + width + ', height: ' + height);
        this.widget.onWidgetContainerResize(width, height);
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    DeploymentEditorPanel.prototype.destroy = function () {
        this.control.destroy();
        this.widget.destroy();

        PanelBaseWithHeader.prototype.destroy.call(this);
        WebGMEGlobal.KeyboardManager.setListener(undefined);
        WebGMEGlobal.Toolbar.refresh();
    };

    DeploymentEditorPanel.prototype.onActivate = function () {
        this.widget.onActivate();
        this.control.onActivate();
        WebGMEGlobal.KeyboardManager.setListener(this.widget);
        WebGMEGlobal.Toolbar.refresh();
    };

    DeploymentEditorPanel.prototype.onDeactivate = function () {
        this.widget.onDeactivate();
        this.control.onDeactivate();
        WebGMEGlobal.KeyboardManager.setListener(undefined);
        WebGMEGlobal.Toolbar.refresh();
    };

    DeploymentEditorPanel.prototype.getNodeID = function () {
        return this.control.getNodeID();
    };

    return DeploymentEditorPanel;
});
